version: '3.8'

services:

  ctl2mimir:
    container_name: ctl2mimir
    build:
      context: ./services/ctl2mimir
      dockerfile: docker/Dockerfile-dev
    ports:
      - 5000:5000
    environment:
      - RUN_MODE=development
      - SQLITE_FILE=ctl2mimir-dev.db
      - SQLITE_TEST_FILE=ctl2mimir-test.db
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./services/elasticsearch
      dockerfile: docker/Dockerfile
    ports:
      - 9200:9200

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: docker/Dockerfile-dev
    ports:
      - 8080:8080
    depends_on:
      - ctl2mimir
      - bragi-status
      - bragi-graphql

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: docker/Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - ctl2mimir
      - bragi-status
      - client

  bragi:
    container_name: bragi
    build:
      context: ./services/bragi
      dockerfile: docker/Dockerfile-dev
    ports:
      - 4000:4000
    environment:
      - BRAGI_ES=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  bragi-status:
    container_name: status
    build:
      context: ./services/bragi-status
      dockerfile: docker/Dockerfile-dev
    ports:
      - 5001:5001
    depends_on:
      - bragi

  bragi-graphql:
    container_name: graphql
    build:
      context: ./services/bragi-graphql
      dockerfile: docker/Dockerfile-dev
    ports:
      - 4001:4001
    depends_on:
      - bragi
