FROM rust:1.44.1-stretch as builder

WORKDIR /srv

RUN apt-get update \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/CanalTP/mimirsbrunn.git

WORKDIR mimirsbrunn

RUN git checkout tags/v1.16.0 -b build

RUN cargo build --release

FROM debian:stretch-slim

ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    RUN_MODE=development \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /srv/mimirsbrunn/target/release/bragi ${APP}/bragi

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./entrypoint.sh"]
